const fs = require('fs')
const file = 'C:/Users/quent/Desktop/my-chinese-app/lib/hsk-fallback-data.ts'
let content = fs.readFileSync(file, 'utf8')

const fixes = [
  // HSK1 残留
  ['dàxuéshēng.', 'dà xué shēng.'],
  ['Zhège ', 'Zhège '],    // 不需要拆，Zhège = 这 + 个
  // HSK3-4 残留
  ['shénme ', 'shén mè '],
  ['shénme?', 'shén mè?'],
  ['shénme.', 'shén mè.'],
  ['shénme,', 'shén mè,'],
  ['Yīshēng', 'Yī shēng'],
  ['Yīshēng,', 'Yī shēng,'],
  ['Yīshēng.', 'Yī shēng.'],
  ['Quèshí ', 'Què shí '],
  ['Quèshí,', 'Què shí,'],
  ['Yǒu méiyǒu', 'Yǒu méi yǒu'],
  ['Yǒu méiyǒu ', 'Yǒu méi yǒu '],
  ['ànshí ', 'àn shí '],
  ['ànshí,', 'àn shí,'],
  ['ànshí?', 'àn shí?'],
  // HSK5-6 残留
  ['Gǎnxiè ', 'Gǎn xiè '],
  ['Búguò,', 'Bú guò,'],
  ['nǎlǐ ', 'nǎ lǐ '],
  ['nǎlǐ,', 'nǎ lǐ,'],
  ['shíxiàn ', 'shí xiàn '],
  ['shíxiàn.', 'shí xiàn.'],
  ['Búcuò,', 'Bú cuò,'],
  ['juéde ', 'jué de '],
  ['zìjǐ ', 'zì jǐ '],
  ['dàilái ', 'dài lái '],
  ['jiàzhí ', 'jià zhí '],
  ['Guānyú ', 'Guān yú '],
  ['Guānyú,', 'Guān yú,'],
  ['shīwù,', 'shī wù,'],
  ['bàoqiàn,', 'bào qiàn,'],
  ['tiān máfan', 'tiān má fan'],
  ['tiān máfan ', 'tiān má fan '],
  ['tiān máfan le.', 'tiān má fan le.'],
  ['Wǒmen ', 'Wǒ men '],
  ['Wǒmen,', 'Wǒ men,'],
  ['Wǒmen.', 'Wǒ men.'],
  ['Zánmen ', 'Zán men '],
  ['Zánmen,', 'Zán men,'],
  ['Wǒmen yīdìng', 'Wǒ men yī dìng'],
  ['yīdìng ', 'yī dìng '],
  ['jiéjìn quánlì', 'jié jìn quán lì'],
  ['jiéjìn ', 'jié jìn '],
  ['quánlì,', 'quán lì,'],
  ['quánlì.', 'quán lì.'],
  ['zhēngqǔ ', 'zhēng qǔ '],
  ['zhēngqǔ,', 'zhēng qǔ,'],
  ['zhēngqǔ.', 'zhēng qǔ.'],
  ['náchū ', 'ná chū '],
  ['kěxíng ', 'kě xíng '],
  ['kěxíng,', 'kě xíng,'],
  ['kěxíng.', 'kě xíng.'],
  ['kèqi ', 'kè qi '],
  ['kèqi,', 'kè qi,'],
  ['kèqi le,', 'kè qi le,'],
  ['kànkan ', 'kàn kan '],
  ['kànkan,', 'kàn kan,'],
  ['yīxià ', 'yī xià '],
  ['yīxià,', 'yī xià,'],
  ['yīxià.', 'yī xià.'],
  ['yīxià?', 'yī xià?'],
  ['yùsuàn ', 'yù suàn '],
  ['yùsuàn,', 'yù suàn,'],
  ['xīwàng ', 'xī wàng '],
  ['xīwàng,', 'xī wàng,'],
  ['xīwàng.', 'xī wàng.'],
  ['hángyè ', 'háng yè '],
  ['kǒubēi,', 'kǒu bēi,'],
  ['yóuqí ', 'yóu qí '],
  ['yóuqí,', 'yóu qí,'],
  ['chuàngxīn ', 'chuàng xīn '],
  ['yánfā ', 'yán fā '],
  ['fāngmiàn ', 'fāng miàn '],
  ['yīzhí ', 'yī zhí '],
  ['qiánliè.', 'qián liè.'],
  ['rúng xìng.', 'róng xìng.'],  // 已部分修复，补充
  ['shì qíng ', 'shì qíng '],  // 已经是正确的
  ['nǎ lǐ,', 'nǎ lǐ,'],
  ['fēi cháng ', 'fēi cháng '],
  ['fēi cháng,', 'fēi cháng,'],
  ['qī dài ', 'qī dài '],
  ['néng gòu ', 'néng gòu '],
  ['hé zuò ', 'hé zuò '],
  ['hé zuò,', 'hé zuò,'],
  ['hé zuò.', 'hé zuò.'],
  ['jiě jué.', 'jiě jué.'],
  ['jiě jué,', 'jiě jué,'],
  ['jiě jué ', 'jiě jué '],
  ['jié jìn', 'jié jìn'],
  ['fāng àn', 'fāng àn'],
  ['wèn tí', 'wèn tí'],
  ['wèn tí.', 'wèn tí.'],
  ['yú kuài!', 'yú kuài!'],
  ['Chéng méng', 'Chéng méng'],
  ['guān zhào,', 'guān zhào,'],
  ['róng xìng.', 'róng xìng.'],
  ['chóng xīn', 'chóng xīn'],
  ['píng gū', 'píng gū'],
  ['bù fèn,', 'bù fèn,'],
  ['yōu huà', 'yōu huà'],
  ['kōng jiān.', 'kōng jiān.'],
  ['jiàn yì', 'jiàn yì'],
  ['huò zhě', 'huò zhě'],
  ['xiū gǎi', 'xiū gǎi'],
  ['yì jiàn?', 'yì jiàn?'],
  ['Lǐ jiě,', 'Lǐ jiě,'],
  ['zhīdào ', 'zhī dào '],
  ['zhīdào,', 'zhī dào,'],
  ['jùtǐ ', 'jù tǐ '],
  ['jùtǐ,', 'jù tǐ,'],
  ['jiàn yì ', 'jiàn yì '],
  ['jiàn yì,', 'jiàn yì,'],
  ['jiàn yì.', 'jiàn yì.'],
  ['huò zhě ', 'huò zhě '],
  ['xiū gǎi ', 'xiū gǎi '],
  ['yì jiàn', 'yì jiàn'],
]

let count = 0
for (const [old, newVal] of fixes) {
  if (content.includes(old)) {
    content = content.split(old).join(newVal)
    count++
    console.log(`✓ ${old} → ${newVal}`)
  }
}
console.log(`\nTotal: ${count} replacements`)
fs.writeFileSync(file, content, 'utf8')
