const fs = require('fs')

const file = 'C:/Users/quent/Desktop/my-chinese-app/lib/hsk-fallback-data.ts'
let content = fs.readFileSync(file, 'utf8')

// 所有需要修复的拼音替换：旧 → 新
const replacements = [
  // HSK 1-2
  ['yào shénme?',      'yào shén mè'],
  ['Nǐ hǎo, yào shénme?', 'Nǐ hǎo, yào shén mè?'],
  ['shénme',           'shén mè'],
  ['xuéshēng ma?',     'xué shēng ma'],
  ['xuéshēng.',        'xué shēng.'],
  ['dàxuéshēng.',      'dà xué shēng.'],
  ['kāfēi.',           'kā fēi.'],
  ['yī bēi kāfēi.',    'yī bēi kā fēi.'],
  ['děng yīxià.',      'děng yī xià.'],
  ['duōshao qián?',    'duō shǎo qián'],
  ['Zhège duōshao qián?', 'Zhè gè duō shǎo qián?'],
  ['nǎr?',             'nǎ ér?'],
  ['nàbiān.',          'nà biān.'],
  ['Zài nàbiān.',      'Zài nà biān.'],

  // HSK 3-4
  ['jīnglǐ,',          'jīng lǐ,'],
  ['Wáng jīnglǐ,',     'Wáng jīng lǐ,'],
  ['bàogào wǒ',        'bào gào wǒ'],
  ['zhǔnbèi hǎo',      'zhǔn bèi hǎo'],
  ['zhuō shang',       'zhuō shang'],
  ['kāihuì de',        'kāi huì de'],
  ['shíhou huì',       'shí hòu huì'],
  ['shénme xūyào',     'shén mè xū yào'],
  ['bāngmáng de',       'bāng máng de'],
  ['zuìjìn jīngcháng', 'zuì jìn jīng cháng'],
  ['tóu téng,',        'tóu téng,'],
  ['wǎnshang yě',     'wǎn shang yě'],
  ['gōngzuò yālì',    'gōng zuò yā lì'],
  ['yǒu méiyǒu',       'yǒu méi yǒu'],
  ['chīfàn?',          'chī fàn?'],
  ['zuìjìn gōngzuò',  'zuì jìn gōng zuò'],
  ['jiābān.',          'jiā bān.'],
  ['yínháng zhànghù.', 'yín háng zhàng hù.'],
  ['shēnfènzhèng',     'shēn fèn zhèng'],
  ['shǒujī hàomǎ.',    'shǒu jī hào mǎ.'],
  ['hùzhào,',          'hù zhào,'],
  ['fángjiān lǐ',      'fáng jiān lǐ'],
  ['miǎnfèi de',       'miǎn fèi de'],
  ['fángkǎ shàngmiàn.', 'fáng kǎ shàng miàn.'],
  ['tuìfáng shíjiān', 'tuì fáng shí jiān'],
  ['shí\'èr diǎn.',   'shí èr diǎn.'],
  ['yīfu néng',        'yī fu néng'],
  ['piányi yīdiǎn?',   'pián yi yī diǎn?'],
  ['zuìdī jià le,',   'zuì dī jià le,'],
  ['huìyuánkǎ,',      'huì yuán kǎ,'],
  ['jiǔ zhé.',         'jiǔ zhé.'],
  ['bàogào',          'bào gào'],
  ['yālì',            'yā lì'],
  // Wi-Fi
  ['Wi-Fi ma?',        'Wi Fi ma?'],
  // HSK 5-6 multi-char pinyin fixes
  ['gōngsī',          'gōng sī'],
  ['gǎnxiè',          'gǎn xiè'],
  ['qiàtán',          'qià tán'],
  ['bǎimáng',         'bǎi máng'],
  ['shuāngyíng',      'shuāng yíng'],
  ['shìyí',           'shì yí'],
  ['hézuò',           'hé zuò'],
  ['fùkuǎn',          'fù kuǎn'],
  ['kǒubēi',          'kǒu bēi'],
  ['chuàngxīn',       'chuàng xīn'],
  ['yánfā',           'yán fā'],
  ['qiánliè',         'qián liè'],
  ['liàojiě',         'liào jiě'],
  ['guìfāng',         'guì fāng'],
  ['jiàzhí',          'jià zhí'],
  ['shīwù',           'shī wù'],
  ['bàoqiàn',         'bào qiàn'],
  ['tiānmáfan',       'tiān má fán'],
  ['bǔjiù',           'bǔ jiù'],
  ['fāngàn',          'fāng àn'],
  ['jiějué',          'jiě jué'],
  ['jiéjìn',          'jié jìn'],
  ['quánlì',          'quán lì'],
  ['zuìduǎn',         'zuì duǎn'],
  ['fāngshì',         'fāng shì'],
  ['shāngliang',      'shāng liang'],
  ['zhōnglái',        'zhōng lái'],
  ['xiāngguān',       'xiāng guān'],
  ['zhíjiē',          'zhí jiē'],
  ['chōuchū',         'chōu chū'],
  ['fēicháng',        'fēi cháng'],
  ['qīdài',           'qī dài'],
  ['nénggòu',         'néng gòu'],
  ['shíxiàn',         'shí xiàn'],
  ['shāngliang shāngliang', 'shāng liang shāng liang'],
  ['zhēngqǔ',         'zhēng qǔ'],
  ['chéngméng',       'chéng méng'],
  ['guānzhào',        'guān zhào'],
  ['róngxìng',        'róng xìng'],
  ['yǐjīng',          'yǐ jīng'],
  ['bùtíng',          'bù tíng'],
  ['jùsuǒ',           'jù suǒ'],
  ['hángyè',          'háng yè'],
  ['zhǔnbèi',         'zhǔn bèi'],
  ['gōngsīyǒu',       'gōng sī yǒu'],
  ['fāngmiàn',        'fāng miàn'],
  ['wǒmen',           'wǒ men'],
  ['zìjǐ',            'zì jǐ'],
  ['wèigōng',         'wèi gōng'],
  ['dàilái',          'dài lái'],
  ['xiànzài',         'xiàn zài'],
  ['jiùshì',          'jiù shì'],
  ['zhège',           'zhè gè'],
  ['zhège',           'zhè gè'],
  ['shìqing',         'shì qíng'],
  ['yǐfāshēng',       'yǐ fā shēng'],
  ['guānjiàn',        'guān jiàn'],
  ['kěxíng',          'kě xíng'],
  ['qièshí',          'qiè shí'],
  ['náchū',           'ná chū'],
  ['shìjiān',         'shí jiān'],
  ['yǒngyuǎn',        'yǒng yuǎn'],
  ['hěnjiǔ',          'hěn jiǔ'],
  ['yánjiū',          'yán jiū'],
  ['yǒuxiē',          'yǒu xiē'],
  ['chéngshú',        'chéng shú'],
  ['dìfang',          'dì fang'],
  ['jùtǐ',            'jù tǐ'],
  ['xiūgǎi',          'xiū gǎi'],
  ['zhēnde',          'zhēn de'],
  ['chóngxīn',        'chóng xīn'],
  ['pínggū',          'píng gū'],
  ['yùsuàn',          'yù suàn'],
  ['bùfèn',           'bù fèn'],
  ['yōuhuà',          'yōu huà'],
  ['kōngjiān',        'kōng jiān'],
  // 遗漏
  ['méiyǒu',           'méi yǒu'],
  ['à nshí',           'àn shí'],  // avoid wrong match
  ['jīngcháng',        'jīng cháng'],
  ['búguò',            'bú guò'],
  ['rúguǒ',            'rú guǒ'],
  ['kěyǐ',             'kě yǐ'],
  ['shíjiān',          'shí jiān'],
  ['fāshēng',          'fā shēng'],
  ['rúhé',             'rú hé'],
  ['wǒmen',            'wǒ men'],
  ['yīdìng',           'yī dìng'],
  ['wèntí',            'wèn tí'],
  ['suǒyǐ',            'suǒ yǐ'],
  ['dànsì',            'dàn sì'],
  ['zhème',            'zhè me'],
  ['shénme',           'shén me'],
  ['nàme',             'nà me'],
  ['zěnme',            'zěn me'],
  ['yǒu shíhou',       'yǒu shí hou'],
  ['suīrán',            'suī rán'],
  ['yīnwèi',            'yīn wèi'],
  ['kěshì',             'kě shì'],
  ['děngdeng',          'děng dēng'],
  ['jiǔjiǔ',            'jiǔ jiǔ'],
  ['zhème',             'zhè me'],
  ['gàosu',             'gào sù'],
  ['gēn běn',           'gēn běn'],
  ['hěnduō',            'hěn duō'],
  ['zhège',             'zhè gè'],
  ['zhèli',             'zhè li'],
  ['nàli',              'nà li'],
  ['jìrán',             'jì rán'],
  ['suīrán',             'suī rán'],
  ['zhēnde',             'zhēn de'],
  ['yǒude',              'yǒu de'],
  ['lìkè',               'lì kè'],
  ['mǎshàng',            'mǎ shàng'],
  ['jìntiān',             'jīn tiān'],
  ['míngtiān',            'míng tiān'],
  ['zuótiān',              'zuó tiān'],
  ['gēn běn',               'gēn běn'],
  ['zhēnde',                'zhēn de'],
]

let changed = 0
replacements.forEach(([oldStr, newStr]) => {
  if (content.includes(oldStr)) {
    content = content.split(oldStr).join(newStr)
    changed++
    console.log(`✅ Fixed: "${oldStr}" → "${newStr}"`)
  }
})

console.log(`\nTotal: ${changed} replacements made`)

fs.writeFileSync(file, content, 'utf8')
console.log('File saved.')
