const fs = require('fs')
const file = 'C:/Users/quent/Desktop/my-chinese-app/lib/hsk-fallback-data.ts'
let content = fs.readFileSync(file, 'utf8')

// Targeted replacements only for known compound pinyin tokens in pinyin field values
// All pinyin tokens that are glued together (no space between syllables)
const fixes = [
  // HSK1-2
  ['shénme,', 'shén mè,'],
  ['shénme?', 'shén mè?'],
  ['shénme.', 'shén mè.'],
  ['xuéshēng ', 'xué shēng '],
  ['xuéshēng,', 'xué shēng,'],
  ['xuéshēng?', 'xué shēng?'],
  ['xuéshēng.', 'xué shēng.'],
  ['dàxuéshēng.', 'dà xué shēng.'],
  ['kāfēi.', 'kā fēi.'],
  ['yīxià.', 'yī xià.'],
  ['yīxià,', 'yī xià,'],
  ['duōshao ', 'duō shǎo '],
  ['duōshao?', 'duō shǎo?'],
  ['nǎr?', 'nǎ ér?'],
  ['nàbiān.', 'nà biān.'],
  ['nàbiān,', 'nà biān,'],
  // HSK3-4
  ['jīnglǐ,', 'jīng lǐ,'],
  ['bàogào ', 'bào gào '],
  ['yǐjīng ', 'yǐ jīng '],
  ['yǐjīng,', 'yǐ jīng,'],
  ['zhǔnbèi ', 'zhǔn bèi '],
  ['Xiàwǔ ', 'Xià wǔ '],
  ['kāihuì ', 'kāi huì '],
  ['shíhou ', 'shí hou '],
  ['wǎnshang ', 'wǎn shang '],
  ['gōngzuò ', 'gōng zuò '],
  ['yālì ', 'yā lì '],
  ['yālì,', 'yā lì,'],
  ['yālì?', 'yā lì?'],
  ['shìfǒu ', 'shì fǒu '],
  ['chīfàn?', 'chī fàn?'],
  ['jiābān.', 'jiā bān.'],
  // HSK5-6
  ['yīgè ', 'yī gè '],
  ['yínháng ', 'yín háng '],
  ['zhànghù.', 'zhàng hù.'],
  ['chūshì ', 'chū shì '],
  ['shēnfènzhèng ', 'shēn fèn zhèng '],
  ['shǒujī ', 'shǒu jī '],
  ['hàomǎ.', 'hào mǎ.'],
  ['hùzhào,', 'hù zhào,'],
  ['kěyǐ ', 'kě yǐ '],
  ['kěyǐ,', 'kě yǐ,'],
  ['kěyǐ?', 'kě yǐ?'],
  ['kěyǐ.', 'kě yǐ.'],
  ['Qǐngwèn ', 'Qǐng wèn '],
  ['Qǐngwèn,', 'Qǐng wèn,'],
  ['fángjiān ', 'fáng jiān '],
  ['fángjiān,', 'fáng jiān,'],
  ['miǎnfèi ', 'miǎn fèi '],
  ['mìmǎ ', 'mì mǎ '],
  ['fángkǎ ', 'fáng kǎ '],
  ['shàngmiàn.', 'shàng miàn.'],
  ['Tuìfáng ', 'Tuì fáng '],
  ['shíjiān ', 'shí jiān '],
  ['shíjiān,', 'shí jiān,'],
  ['shíjiān.', 'shí jiān.'],
  ['zhōngwǔ ', 'zhōng wǔ '],
  // shí粘在èr前面的情况在后面单独处理
  ['yīfu ', 'yī fu '],
  ['piányi ', 'pián yi '],
  ['yīdiǎn?', 'yī diǎn?'],
  ['yīdiǎn,', 'yī diǎn,'],
  ['yīdiǎn.', 'yī diǎn.'],
  ['zuìdī ', 'zuì dī '],
  ['búguò ', 'bú guò '],
  ['búguò,', 'bú guò,'],
  ['rúguǒ ', 'rú guǒ '],
  ['huìyuánkǎ,', 'huì yuán kǎ,'],
  ['gōngsī ', 'gōng sī '],
  ['gōngsī,', 'gōng sī,'],
  ['gōngsī.', 'gōng sī.'],
  ['bǎimáng ', 'bǎi máng '],
  ['chōuchū ', 'chōu chū '],
  ['qiàtán ', 'qià tán '],
  ['hézuò ', 'hé zuò '],
  ['hézuò,', 'hé zuò,'],
  ['hézuò.', 'hé zuò.'],
  ['shìyí.', 'shì yí.'],
  ['nǎlǐ ', 'nǎ lǐ '],
  ['nǎlǐ,', 'nǎ lǐ,'],
  ['fēicháng ', 'fēi cháng '],
  ['qīdài ', 'qī dài '],
  ['nénggòu ', 'néng gòu '],
  ['shuāngyíng.', 'shuāng yíng.'],
  ['guānyú ', 'guān yú '],
  ['guānyú,', 'guān yú,'],
  ['fùkuǎn ', 'fù kuǎn '],
  ['fāngshì,', 'fāng shì,'],
  ['kǒngpà ', 'kǒng pà '],
  ['shāngliang ', 'shāng liang '],
  ['shāngliang.', 'shāng liang.'],
  ['shāngliang,', 'shāng liang,'],
  ['wǒmen ', 'wǒ men '],
  ['wǒmen,', 'wǒ men,'],
  ['wǒmen.', 'wǒ men.'],
  ['shìqing ', 'shì qíng '],
  ['fāshēng ', 'fā shēng '],
  ['guānjiàn ', 'guān jiàn '],
  ['guānjiàn,', 'guān jiàn,'],
  ['bǔjiù.', 'bǔ jiù.'],
  ['jiějué ', 'jiě jué '],
  ['jiějué.', 'jiě jué.'],
  ['fāngàn.', 'fāng àn.'],
  ['fāngàn,', 'fāng àn,'],
  ['wèntí.', 'wèn tí.'],
  ['wèntí?', 'wèn tí?'],
  ['yúkuài!', 'yú kuài!'],
  ['Chéngméng ', 'Chéng méng '],
  ['guānzhào,', 'guān zhào,'],
  ['róngxìng.', 'róng xìng.'],
  ['chóngxīn ', 'chóng xīn '],
  ['pínggū ', 'píng gū '],
  ['bùfèn,', 'bù fèn,'],
  ['yōuhuà ', 'yōu huà '],
  ['kōngjiān.', 'kōng jiān.'],
  ['jiànyì ', 'jiàn yì '],
  ['huòzhě ', 'huò zhě '],
  ['xiūgǎi ', 'xiū gǎi '],
  ['yìjiàn?', 'yì jiàn?'],
  ['Lǐjiě,', 'Lǐ jiě,'],
  ['xūyào ', 'xū yào '],
  ['bāngmáng ', 'bāng máng '],
  ['bāngmáng,', 'bāng máng,'],
  ['bāngmáng.', 'bāng máng.'],
  ['zuìjìn ', 'zuì jìn '],
  ['jīngcháng ', 'jīng cháng '],
  ['jīngcháng,', 'jīng cháng,'],
  ['jīngcháng.', 'jīng cháng.'],
  ['tóuténg,', 'tóu téng,'],
  ['Zánmen ', 'Zán men '],
  ['xiānsheng,', 'xiān sheng,'],
  ['bǐjiào,', 'bǐ jiào,'],
  // 大写版本（已拆分的不需要额外处理）
  ['Èrshí ', 'Èr shí '],
  ['Dìtiě ', 'Dì tiě '],
  ['Zàinàbiān.', 'Zài nà biān.'],
  // Wi-Fi
  ['Wi-Fi', 'Wi Fi'],
  ['wi-fi', 'wi fi'],
]

let count = 0
for (const [old, newVal] of fixes) {
  if (content.includes(old)) {
    content = content.split(old).join(newVal)
    count++
    console.log(`✓ ${old} → ${newVal}`)
  }
}
console.log(`\nTotal: ${count} replacements`)
fs.writeFileSync(file, content, 'utf8')
