// 修复所有残留的大写拼音 + 未拆复合音节
const fs = require('fs')

const file = 'C:/Users/quent/Desktop/my-chinese-app/lib/hsk-fallback-data.ts'
let content = fs.readFileSync(file, 'utf8')

// 按长度降序排列（先匹配长的再匹配短的，避免部分替换）
const fixes = [
  // 大写开头 → 小写（同时拆复合词）
  ['Yīshēng,',         'yī shēng,'],
  ['Yīshēng.',         'yī shēng.'],
  ['Zhège',            'zhè gè'],
  ['Zhège.',           'zhè gè.'],
  ['Èrshí',            'èr shí'],
  ['Èrshí.',           'èr shí.'],
  ['Dìtiě',            'dì tiě'],
  ['Dìtiě.',           'dì tiě.'],
  ['Hěn hǎo,',         'hěn hǎo,'],
  ['Hěn hǎo.',         'hěn hǎo.'],
  ['Hǎo de,',          'hǎo de,'],
  ['Hǎo de.',          'hǎo de.'],
  ['Hǎo de',           'hǎo de'],
  ['Xiàwǔ',            'xià wǔ'],
  ['Xiàwǔ.',           'xià wǔ.'],
  ['Yǒu de,',          'yǒu de,'],
  ['Yǒu de.',          'yǒu de.'],
  ['Yǒu méiyǒu',      'yǒu méi yǒu'],
  ['Yǒu méiyǒu.',     'yǒu méi yǒu.'],
  ['Quèshí',           'què shí'],
  ['Quèshí,',          'què shí,'],
  ['Quèshí.',          'què shí.'],
  ['Nǐ hǎo,',          'nǐ hǎo,'],
  ['Nǐ hǎo.',          'nǐ hǎo.'],
  ['Qǐng chūshì',      'qǐng chū shì'],
  ['Qǐng chūshì.',     'qǐng chū shì.'],
  ['Qǐngwèn',          'qǐng wèn'],
  ['Qǐngwèn.',         'qǐng wèn.'],
  ['Gǎnxiè',           'gǎn xiè'],
  ['Gǎnxiè.',          'gǎn xiè.'],
  ['Nǎlǐ nǎlǐ,',       'nǎ lǐ nǎ lǐ,'],
  ['Nǎlǐ nǎlǐ.',       'nǎ lǐ nǎ lǐ.'],
  ['Búguò,',           'bú guò,'],
  ['Búguò.',           'bú guò.'],
  ['Guānyú',           'guān yú'],
  ['Guānyú,',          'guān yú,'],
  ['Guānyú.',          'guān yú.'],
  ['Jù wǒ',            'jù wǒ'],
  ['Jù wǒ,',           'jù wǒ,'],
  ['Jù wǒ.',           'jù wǒ.'],
  ['Búcuò,',           'bú cuò,'],
  ['Búcuò.',           'bú cuò.'],
  ['Jìrán',            'jì rán'],
  ['Jìrán,',           'jì rán,'],
  ['Jìrán.',           'jì rán.'],
  ['Xīwàng',           'xī wàng'],
  ['Xīwàng,',          'xī wàng,'],
  ['Xīwàng.',          'xī wàng.'],
  ['Wǒmen',            'wǒ men'],
  ['Wǒmen,',           'wǒ men,'],
  ['Wǒmen.',           'wǒ men.'],
  ['Zhāng zǒng,',      'zhāng zǒng,'],
  ['Zhāng zǒng.',      'zhāng zǒng.'],
  ['Chéngméng',        'chéng méng'],
  ['Chéngméng,',       'chéng méng,'],
  ['Chéngméng.',       'chéng méng.'],
  ['Nín tài',          'nín tài'],
  ['Nín tài,',         'nín tài,'],
  ['Nín tài.',         'nín tài.'],
  ['Lǐjiě,',           'lǐ jiě,'],
  ['Lǐjiě.',           'lǐ jiě.'],
  ['Yúkuài',           'yú kuài'],
  ['Yúkuài!',          'yú kuài!'],
  ['Zánmen',           'zán men'],
  ['Zánmen',           'zán men'],
  // 未拆复合词
  ['dàxué shēng.',     'dà xué shēng.'],
  ['dàxuéshēng.',      'dà xué shēng.'],
  ['xūyào',            'xū yào'],
  ['xūyào.',           'xū yào.'],
  ['xūyào wǒ',         'xū yào wǒ'],
  ['à nshí',           'àn shí'],
  ['à nshí chī',       'àn shí chī'],
  ['mìmǎ',             'mì mǎ'],
  ['mìmǎ zài',         'mì mǎ zài'],
  ['Tuìfáng',          'tuì fáng'],
  ['Tuìfáng shí',      'tuì fáng shí'],
  ['zhōngwǔ',          'zhōng wǔ'],
  ['zhōngwǔ shí',      'zhōng wǔ shí'],
  ['kǒngpà',           'kǒng pà'],
  ['kǒngpà wǒ',        'kǒng pà wǒ'],
  ['yóuqí',            'yóu qí'],
  ['yóuqí zài',        'yóu qí zài'],
  ['yīzhí zǒu',        'yī zhí zǒu'],
  ['juéde',            'jué de'],
  ['juéde zì',         'jué de zì'],
  ['tiānmáfan',        'tiān má fán'],
  ['tiānmáfan le.',    'tiān má fán le.'],
  ['kèqi',             'kè qi'],
  ['kèqi le,',         'kè qi le,'],
  ['kèqi le.',         'kè qi le.'],
  ['zhīdào',           'zhī dào'],
  ['zhīdào guì',       'zhī dào guì'],
  ['jiànyì',           'jiàn yì'],
  ['jiànyì huò',       'jiàn yì huò'],
  ['huòzhě',           'huò zhě'],
  ['huòzhě xiū',       'huò zhě xiū'],
  ['yìjiàn?',          'yì jiàn?'],
  ['yìjiàn.',          'yì jiàn.'],
  ['kànkan',           'kàn kan'],
  ['kànkan shì',       'kàn kan shì'],
  ['shìfǒu',           'shì fǒu'],
  ['shìfǒu yǒu',       'shì fǒu yǒu'],
  ['yīxià',            'yī xià'],
  ['yīxià yù',         'yī xià yù'],
  ['yùsuàn',           'yù suàn'],
  ['yùsuàn bù',        'yù suàn bù'],
  ['fāngàn',           'fāng àn'],
  ['fāngàn',           'fāng àn'],
  ['fāngàn.',          'fāng àn.'],
  ['jiějué fāngàn',    'jiě jué fāng àn'],
  ['jiějué fāngàn.',   'jiě jué fāng àn.'],
  ['wèntí.',           'wèn tí.'],
  ['wèntí.',           'wèn tí.'],
  ['nǎ lǐ nǎ lǐ,',     'nǎ lǐ nǎ lǐ,'],
  ['nǎ lǐ nǎ lǐ.',     'nǎ lǐ nǎ lǐ.'],
]

let changed = 0
fixes.forEach(([oldStr, newStr]) => {
  if (content.includes(oldStr)) {
    content = content.split(oldStr).join(newStr)
    changed++
    console.log(`✅ "${oldStr}" → "${newStr}"`)
  }
})

console.log(`\nTotal: ${changed} replacements made`)
fs.writeFileSync(file, content, 'utf8')
